### ISSUE TITLE
Can't control logging from Swift

### ISSUE THREAD

**Issue by cwilper** [Lejdborg/NMSSH#100]
NMSSH works fine for me from Swift, but I was unable to control logging by calling the static property NMSSHLogger.logger. I believe this is because Swift doesn't support them. It would be great to provide a static accessor method for this as well.

I was able to get around this, and access the shared logging config from Swift by just adding the following to NMSSHLogger.m (and the corresponding declaration to NMSSHLogger.h)

+ (instancetype)sharedInstance {
  return NMSSHLogger.logger;
}

**Comment by crazyquark** [comment]
I have this issue too. I will try this workaround.
Seems static/class vars are not exported to Swift.

**Comment by Razinsky** [comment]
Can you paste the exact code needed in the NMSSHLogger.h and NMSSHLogger.m files please?

Tried <code>+ (NMSSHLogger *)sharedInstance { return NMSSHLogger.logger; }</code>
and <code>+ (NMSSHLogger *)sharedInstance;</code>

but I get that <pre>'NSInvalidArgumentException', reason: '+[NMSSHLogger sharedInstance]: unrecognized selector sent to class 0x10ef95f48'</pre>

I'm so bad with obj-c!

**Comment by crazyquark** [comment]
Hi,
That's still a static method and Swift won't see it, you need this(like cwilper said above):
```
-(instancetype) sharedInstance { return NMSSHLogger.logger; }
```

The trick is to have an instance method that accesses internally the static method.

**Comment by Razinsky** [comment]
Ok. Now how do I call that sharedInstance? I tried several things and that just doesn't work..

<pre>NMSSHLogger().sharedInstance().logLevel = NMSSHLogLevel.Info</pre>
seems all right but it makes my app crash: 
<pre>Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NMSSHLogger sharedInstance]: unrecognized selector sent to instance</pre>

Thanks again for your help.

**Comment by crazyquark** [comment]
I am sorry, I think I misled you, turns out it was a static method after all! 




I had this in my .h:
```
+(instancetype)sharedInstance;
```
And this in my .m:


```
+(instancetype)sharedInstance
{
    return NMSSHLogger.logger;
}
```
I access mine like this, in Swift:
```
NMSSHLogger.sharedInstance().enabled = false;
```

Would it be easier if I just pushed a merge request?.

**Comment by crazyquark** [comment]
See my pull request: https://github.com/Lejdborg/NMSSH/pull/123

**Comment by Razinsky** [comment]
I modified the files to fit your pull request and now call with <code>NMSSHLogger.sharedLogger().enabled = false</code> but I still got my app crashing every time!

<pre>+[NMSSHLogger sharedLogger]: unrecognized selector sent to class 0x10b47cf48</pre>

What could cause that?

**Comment by Lejdborg** [comment]
In the pull request the method is currently called `+sharedInstance` so `NMSSHLogger.sharedInstance().enabled = false` should work for you.

**Comment by Lejdborg** [comment]
`unrecognized selector sent to class` means you tried to call a static method that does not exist on the class.

**Comment by crazyquark** [comment]
sharedLogger does not exist in my pull request...

**Comment by crazyquark** [comment]
I made a new pull request, renaming logger to sharedLogger, as per @Lejdborg instructions: https://github.com/Lejdborg/NMSSH/pull/125

**Comment by crazyquark** [comment]
@cwilper does the proposed fix work for you?

**Comment by cwilper** [comment]
@crazyquark i'm not in a position to test on my swift project at the moment, but I took a look at the PR and it looked good. Thanks!
