### ISSUE TITLE
Correct usage of NMSSH in Swift iOS Application

### ISSUE THREAD

**Issue by svenover** [Lejdborg/NMSSH#104]
Hello,

I follow the instruction to build the NMSSH.framework. All was build successfully with Xcode 6.1.

Then I tried to add the framework to my simple swift ios app as described in the manual.
1. Add file NMSSH.framework to the project
2. Add the needed libraries (NMSSH.framework, libz.dylib, CFNetwork.framework)  to the Build Phases - Link Binary With Libraries
So far it worked well.
My problem is the following one which caused an error.
Add #import <NMSSH/NMSSH.h> to your source file.
Please see screenshot for the error.
![image](https://cloud.githubusercontent.com/assets/8537968/4906654/d1008a22-645a-11e4-9e8a-6c95f4e0162c.png)
I also tried the fix without success.

I hope anyone can help me to add the NMSSH.framework to my swift ios app.

With Xcode 5 all was working fine for me.

Many thanks in advance.
Sven

**Comment by federom** [comment]
Sven,

Take a look to this

http://www.learnswiftonline.com/getting-started/adding-swift-bridging-header/
