### ISSUE TITLE
Problem building framework ios

### ISSUE THREAD

**Issue by giuliomol** [Lejdborg/NMSSH#110]
Hi,

i followed the steps in your documentation: https://github.com/Lejdborg/NMSSH/wiki/Build-and-use-in-your-iOS-project

but when i build, the NMSSH.framework remains red
![schermata 2014-12-17 alle 19 42 14](https://cloud.githubusercontent.com/assets/10224252/5476707/d8a6dbe6-8624-11e4-8468-be0b50c63c09.png)

What can i do?
Thanks a lot!
G.

**Comment by Jojco** [comment]
Same problem for me...

**Comment by Jojco** [comment]
Actually select Product>Scheme>NMSSH Framework, then build it.
