### ISSUE TITLE
Connecting to SSH on system which support only KeyboardInteractive

### ISSUE THREAD

**Issue by thanacpr** [Lejdborg/NMSSH#112]
Hi,

I'm checking my system for authentication support from command 
    NSLog(@"Auth methods: %@", session.supportedAuthenticationMethods);

and below is the result: 

2015-01-12 01:29:38.502 SSH_Proj[6517:81817] Auth methods: (
    publickey,
    "keyboard-interactive"
)

I'm trying to use this function authenticateByKeyboardInteractiveUsingBlock:<#^NSString *(NSString *request)authenticationBlock#> to provide password to system but I did not know how to pass parameter. 

Can someone throw me some light ?

**Comment by Lejdborg** [comment]
```
NMSSHSession *session = [NMSSHSession connectToHost:@"127.0.0.1:22"  withUsername:@"user"];

if (session.isConnected) {
    NSLog(@"Successfully created a new session");
    [session authenticateByKeyboardInteractiveUsingBlock:^(NSString *request) {
        NSLog(@"%@", request);
        return @"pass";
    }
}
```

**Comment by thanacpr** [comment]
Thanks it's working now.
