### ISSUE TITLE
File upload problem

### ISSUE THREAD

**Issue by amckean** [Lejdborg/NMSSH#113]
I'm just starting to use NMSSH, but I have encountered a problem that stumps me. I can connect and authenticate with my remote host, but uploadFile:to: always returns NO and the file does not appear in my remote host. It's a simple text file that I am trying to upload. Any thoughts?

**Comment by Lejdborg** [comment]
Your server might not accept SCP connections. You should check the server config.

**Comment by amckean** [comment]
I have been using DLSFTP until now with no problems. It is only as I am forced to move (by Apple) to 64-bit (arm64) that I have been motivated to change to NMSSH. I will check, though. Thanks for your response.

Alan
