### ISSUE TITLE
armv7 support

### ISSUE THREAD

**Issue by amckean** [Lejdborg/NMSSH#114]
I have been doing development in the simulator. When I ran into the file upload problem that I posted a bit ago, I decided to try it on a device to see if it made any difference. When I run on the device, I get a linker error:ld: warning: ignoring file .../NMSSH.framework/NMSSH, missing required architecture armv7 in file .../NMSSH.framework/NMSSH (2 slices). Can anyone explain? Does it really only run in arm64?

**Comment by Lejdborg** [comment]
If built for the simulator it might not work on a device since the simulator uses a completely different architecture. You need to rebuild the framework for the device.

**Comment by solarissf** [comment]
I have the opposite problem, I think mine was previously build for device so now I need to rebuild for the simulator.  Can you please tell me how to rebuild the framework?

**Comment by amckean** [comment]
I will let you know when I succeed.

**Comment by Frugghi** [comment]
You should follow the [wiki guide](https://github.com/Lejdborg/NMSSH/wiki/Build-and-use-in-your-iOS-project), the framework should be universal...

**Comment by solarissf** [comment]
I ended up installing from PODS and both simulator and device both work now

**Comment by iCyberPaul** [comment]
To maybe help someone else.
I had not realised that I needed to build one copy of the NMSSH.framework for a simulator target AND another for the iOS device target.

**Comment by Frugghi** [comment]
The [wiki guide](https://github.com/Lejdborg/NMSSH/wiki/Build-and-use-in-your-iOS-project) show the steps to build a framework for both the device and the simulator, otherwise Xcode will build the framework only for the active architecture.
