### ISSUE TITLE
Building IOS Framework does nothing.

### ISSUE THREAD

**Issue by darryljackman** [Lejdborg/NMSSH#118]
As per instructions, I opened the Project, selected the Target, did Project -> Build, but "Products" folder does not appear with Framework file as instructions dictate.

**Comment by bhr** [comment]
Did you already manage to build the framework (because you already opened #119)?

**Comment by darryljackman** [comment]
I do have it working, but not by using exact steps in instructions..

Following the instructions to open the "NMSSH-IOS" project, select the target in the top left, then build, but the framework file does not appear in a "Products" folder as indicated in the steps and images.

I tried normal build, plus the others, but no where was this "Products" folder to be found which was supposed to have the "NMSSH.framework" file.

What I did after was open the NMSSH-IOS again, and "right-clicked" the "NMSSH.framework" file inside the XCode, then clicked "Show in Finder".

This brought me to the file, which was located in a sub, sub, sub, sub folder inside the XCode.app Package as part of iOS SDK files.

I was then able to copy this file successfully into my new project and everything worked as expected.


Thank you for the quick reply, and don't know if it was something with my XCode, or some combinations of setting or other things installed..

**Comment by coernel** [comment]
I tried to follow his steps but they can't help me. I tried using Finder to find NMSSH.framework but to no avail. XCode shows the file as missing (red) and although there are no errors when building, I don't get a resulting file

**Comment by coernel** [comment]
Forget t, found it. For everyone else: I solved it by using an iOS device as deployment target, not the iOS simulator!

**Comment by thomas-pk** [comment]
Tried finding NMSSH.framework in Finder but no success.  Xcode shows it is as missing in red.  To use iOS device as deployment target instead of the simulator, do I need to sign up for an apple developer account?  I don't have one at the moment, that's the reason I'm asking.  Thanks in advance.

**Comment by Lejdborg** [comment]
@thomas-pk Yes, you need a (paid) iOS developer account to build against a device.

**Comment by codingTheHole** [comment]
Brilliant, coernel, I'd never have thought of that. Thanks
