### ISSUE TITLE
Help with channel.execute in Swift

### ISSUE THREAD

**Issue by Razinsky** [Lejdborg/NMSSH#120]
Can someone help me understand how to port the obj-c code to Swift? I'm very new at developing for iOS and I am still learning Swift.

I succeeded at connecting to a SSH client but I always get the <code>fatal error: unexpectedly found nil while unwrapping an Optional value</code> error with this part:

<pre>var error: NSErrorPointer?
var response: String? = session.channel.execute("ls -la", error: error!)</pre>

I feel so stupid asking help for that but I have tried so many things already and nothing worked :(

Thanks in advance.

P.S. Maybe porting all your example to Swift could help other people like me?

**Comment by Frugghi** [comment]
It's not a NMSSH issue but this is the solution:
```Swift
var error: NSError?
var response: String? = session.channel.execute("ls -la", error: &error)
```
