### ISSUE TITLE
Could not open file at path when creating directory

### ISSUE THREAD

**Issue by Hobsie85** [Lejdborg/NMSSH#122]
Hi,

Just started using NMSSH - great wrapper btw, very easy to set up and get going!

I've got an odd issue when attempting to create a directory using NMSFTP createDirectoryAtPath()

```
    NMSSHSession *session = [NMSSHSession connectToHost:hostAddress withUsername:username];
    
    if (session.isConnected) {
        [session authenticateByPassword:password];
        if (session.isAuthorized) {
            printf_console("Authentication succeeded\n");
        }
    }
    
    NMSFTP *sftpSession = [NMSFTP connectWithSession:session];
    
    bool success = [sftpSession directoryExistsAtPath:[NSString stringWithFormat:@"data/%@", newFolder]];
    
    if (!success) {
        printf_console("No folder at data/TEST will attempt to create it.\n");
        success = [sftpSession createDirectoryAtPath:@"data/TEST"];
    }
    
    [sftpSession disconnect];
    [session disconnect];
```

Everything seems to work as expected, I get connected to the server, authenticated, it even successfully creates the directory and createDirectoryAtPath returns true indicating that it has succeeded - however, I noticed in the output i'm getting this message:

> No folder at data/TEST will attempt to create it.
> NMSSH: Could not open file at path data/TEST (Error -31: Failed opening remote file)
> NMSSH: SFTP error 2

Well I'm not trying to open a file at that location - I quite literally just created a directory!

Some other tidbits of information - The user is locked down to only be able to read/write within that data folder (home/data/) and I've disabled shell access (actually took me a wee while to realise the examples given use scp rather than sftp put/get).

Regards
Hobsie

**Comment by Frugghi** [comment]
I can't test it right now but I guess the issue is that a path of a directory must end with a "/".
```ObjectiveC
if (!success) {
    printf_console("No folder at data/TEST will attempt to create it.\n");
    success = [sftpSession createDirectoryAtPath:@"data/TEST/"];
}
```

**Comment by deepukjayan** [comment]
This issue still exists. I tried with a "/" at the end and without. Same error:  NMSSH: Could not open file at path /dev/test/ (Error -31: Failed opening remote file)
