### ISSUE TITLE
NMSSH doesn't compile in Swift

### ISSUE THREAD

**Issue by gurinderhans** [Lejdborg/NMSSH#126]
![screen shot 2015-03-20 at 8 44 01 pm](https://cloud.githubusercontent.com/assets/3400083/6763628/a82a2010-cf42-11e4-911e-b674801819cf.png)

I was able to compile the NMSSH framework nicely without any build errors / warnings. Then I imported it into a blank Objective-C project and it worked perfectly. I was able to connect to ssh server fine. However if I import the same framework into a blank Swift application (using a Bridging-Header) I get those warnings above when I try to build/run the app. Can someone help me here? Thanks!
(I am giving up after straight two hours of endless trying to get it to work plus a couple before that I spent getting the framework to build, but that is perfect now :D )

**Comment by gurinderhans** [comment]
And then it ~magically~ worked. :D

**Comment by Lejdborg** [comment]
You need to `#import <Foundation/Foundation.h>`
