### ISSUE TITLE
After executing "downloadFile:to:" all files disappeared from my Desktop.

### ISSUE THREAD

**Issue by AlphaHack** [Lejdborg/NMSSH#129]
After running this method all files that were on the desktop disappeared and the file "dump01.bin" wasn't there. The files that were on the desktop didn't even go to the trash can... Where are they???? Can I recover it?? 

/home/pi/dump01.bin is in the raspberry and /Users/home/desktop is my Mac mini.

- (IBAction)btnDumpNOR:(NSButton *)sender {
    [session.channel downloadFile:@"/home/pi/dump01.bin" to:@"/Users/home/desktop"];
    NSLog(@"Dump is finished!!!");
  
}

**Comment by holmesrg** [comment]
Capital D for desktop?

**Comment by AlphaHack** [comment]
Ok but the problem is that all files were gone!!! And I must recover them

Em quinta-feira, 14 de maio de 2015, Ron Holmes <notifications@github.com>
escreveu:

> Capital D for desktop?
>
> Sent from my iPhone
>
> > On 15 May 2015, at 10:08 am, AlphaHack <notifications@github.com

**Comment by AlphaHack** [comment]
I did a test again and the same happened. I created a dummy.txt file and placed it on my Desktop. And when I executed the method the file just disappeared. I checked the console and it outputs this message: "2015-05-15 07:38:16.994 SSH[610:20446] NMSSH: A file already exists at /Users/home/Desktop, it will be overwritten". So, there is a problem with it that is overwriting my stuff placed on Desktop.

**Comment by Frugghi** [comment]
`@"/Users/home/desktop"` is a path to a file, you should use `@"/Users/home/desktop/"` or `@"/Users/home/desktop/dump01.bin"`
 Example:
```ObjectiveC
-(IBAction)btnDumpNOR:(NSButton *)sender {
    [session.channel downloadFile:@"/home/pi/dump01.bin" to:@"/Users/home/desktop/"];
    NSLog(@"Dump is finished!!!");
}
```
