### ISSUE TITLE
Issue when trying to connect to host with special character in name

### ISSUE THREAD

**Issue by mountsi** [Lejdborg/NMSSH#130]
I can successfully connect to my host "mbstest.local"

###
NMSSH: Start mbstest.local. resolution
NMSSH: Socket connection to 192.168.178.41 on port 22 succesful
NMSSH: Remote host banner is SSH-2.0-OpenSSH_6.2
NMSSH: The host's fingerprint is xxx
NMSSH: SSH session started
###

Changing the name of this computer will cause NMSSH to fail connection to this host 
###
NMSSH: Start mbs'test.local. resolution
NMSSH: Unable to resolve host mbs'test.local.
NMSSH: Failure establishing socket connection
NMSSH: Disconnected
###

It seems that special characters like '  or blank will cause this issue.

**Comment by Frugghi** [comment]
According to [RFC 952](http://tools.ietf.org/html/rfc952) your host name is not a valid host name:
```
A "name" (Net, Host, Gateway, or Domain name) is a text string up
to 24 characters drawn from the alphabet (A-Z), digits (0-9), minus
sign (-), and period (.).
```

**Comment by mountsi** [comment]
It's the default hostname in Mac OS X after installation (i.e. "user's MacBook Air" )

**Comment by Frugghi** [comment]
On OS X the host name for `user's MacBook Air` is `users-MacBook-Air.local`
