### ISSUE TITLE
What is the difference between session and channel when downloading

### ISSUE THREAD

**Issue by iCyberPaul** [Lejdborg/NMSSH#132]
I could not get the download a file to work when using a NMSFTP from the connection's session

    [self connectToServer:host usingUsername:username andPassword:password];
    if (self.session.connected){
        NMSFTP *nmsft;
        nmsft = [NMSFTP connectWithSession:self.session];
        BOOL success = [nmsft writeFileAtPath:remotefile toFileAtPath:localfile];
        return success;
    } else {
        return false;
    }

But I could get it working using the session's channel

    if (self.session.connected){
        NMSFTP *nmsft;
        nmsft = [NMSFTP connectWithSession:self.session];
        BOOL success = [self.session.channel downloadFile:remotefile to:localfile];
        return success;
    } else {
        return false;
    }

I have only used the NMSFTP from the session for uploading of files and for downloading data.
Can you explain the difference, please.

**Comment by Lejdborg** [comment]
The session is the SSH session. You need it for both NMSFTP and NMSSHChannel.

In this case it is the difference between downloading via SFTP (NMSFTP) and SCP (NMSSHChannel).
