### ISSUE TITLE
libssh2 out of date

### ISSUE THREAD

**Issue by gnachman** [Lejdborg/NMSSH#135]
There have been quite a few bug fixes since the libssh2 that included in NMSSH was built. I don't mind building my own but I don't think there are docs on how to best build it for NMSSH.

**Comment by Frugghi** [comment]
I built the library using a script I wrote, you can find it [here](https://github.com/Frugghi/iSSH2). I'll update the library as soon as possible!

**Comment by gnachman** [comment]
It looks like there's a newer version of OpenSSL than what that page refers to. OpenSSL is scary. Thanks, @Frugghi

**Comment by gnachman** [comment]
This commit only affected iOS, not Mac OS. Could you update the Mac OS version as well?

**Comment by Frugghi** [comment]
On OSX NMSSH uses the dylib shipped with the os.

**Comment by gnachman** [comment]
I see that I wrote “OpenSSL” in my Jun 21 comment, and that is indeed linked in dynamically. Sorry for the confusion! My more recent comment was about libssh. NMSSH's version was built on 1/19/14 while the latest version at http://www.libssh2.org/download/ is from June of 2015

Hm, there's a libbsh2.a here: https://github.com/NMSSH/NMSSH/blob/master/NMSSH-OSX/Libraries/lib/libssh2.a

And it seems to get linked:
<img width="1114" alt="screen shot 2016-01-06 at 5 59 01 pm" src="https://cloud.githubusercontent.com/assets/427546/12160272/330b7aa2-b49f-11e5-901c-9b34eb39e053.png">

**Comment by Frugghi** [comment]
Oh, I thought you wanted an update of OpenSSL indeed. I'll work on it :+1:

**Comment by gnachman** [comment]
Thanks!!

**Comment by gnachman** [comment]
@Frugghi There's a serious problem in the current version of libbsh2: it corrupts the known_hosts file. It was fixed upstream (https://github.com/libssh2/libssh2/issues/85#issuecomment-186921307). I don't mind building it myself, but I got lost in automake hell trying to figure it out :(. If you have some scripts I can use as a starting point I'll send you a PR.

**Comment by Frugghi** [comment]
@gnachman I use a script I wrote, you can find it [here](https://github.com/Frugghi/iSSH2). I added an option to build for OSX but I've not tested it with NMSSH yet.

**Comment by gnachman** [comment]
Looks good. I used these options:
````
iSSH2.sh --archs=x86_64 --min-version=10.7 --sdk-version=10.11 --osx
````
libssh2 uses some symbols that aren't in the OS's release of openssl, so I had to link the libcrypto static library into NMSSH.

**Comment by gnachman** [comment]
@Frugghi I see you updated libssh to version 1.6 in commit 9b6f188693966c9840be319771d0baeb8171f2a2. Why not 1.7?

**Comment by Frugghi** [comment]
I built the library on February 23, probably I did that before 1.7 was released. I hadn't checked if a newer version was released before updating the podspec on March 8.

**Comment by gnachman** [comment]
1.7 came on on 2/23. You lost the race by a nose! :)
