### ISSUE TITLE
Is NMSSH has swift version

### ISSUE THREAD

**Issue by taug** [Lejdborg/NMSSH#137]
I want to use libssh2 in my swift project.NMSSH is a popular libssh2 wrapper,but NMSSH is write in object-c.Is NMSSH has a swift version.

**Comment by Lejdborg** [comment]
You can use NMSSH from Swift. Swift and Objective-C work very nicely together.

**Comment by taug** [comment]
Ok，thanks,I will have a try.

**Comment by yohochen** [comment]
Hi, I know its been a while. 
But how did you do anything to write/data data using NMSSH on swift?
