### ISSUE TITLE
How to use iOS delegate and callback methods from NMSSH library?

### ISSUE THREAD

**Issue by mohammedmoinuddin80** [Lejdborg/NMSSH#143]
I'm trying to use delegate methods from NMSSH library in iOS but could not get it working. Let's take an example.

CustomViewController.h
```ObjectiveC
#import <UIKit/UIKit.h>
#import <NMSSH/NMSSH.h>

@interface CustomViewController : UIViewController<NMSSHSessionDelegate, NMSSHChannelDelegate>

- (IBAction)connectButton:(UIButton *)sender;

@end
```
CustomViewController.m
```ObjectiveC
#import "CustomViewController.h"

@implementation CustomViewController

-(void)viewDidLoad{
    [super viewDidLoad];
}

- (IBAction)connectButton:(UIButton *)sender {

        [self serverConnect:@"10.0.0.1"];

}

-(void)serverConnect:(NSString *)address{

NMSSHSession *session = [NMSSHSession connectToHost:address withUsername:@"username"];

NMSSHChannel *myChannel = [[NMSSHChannel alloc]init];

    if (session.isConnected) {
        [session authenticateByPassword:@"password"];

        if (session.isAuthorized) {
            NSLog(@"Authentication succeeded");
            [session setDelegate:self];
        [myChannel setDelegate:self];
        }
    }

        NSError *error = nil;
        //session.channel.requestPty = YES; (tried and later ignored)
        NSString *response = [session.channel execute:@"mkdir" error:&error];
        NSLog(@"Response from device: %@", response);
}

- (void)session:(NMSSHSession *)session didDisconnectWithError:(NSError *)error{
    NSLog(@"log if session disconnects...Delegate method");
}

- (void)channel:(NMSSHChannel *)channel didReadError:(NSString *)error{
    NSLog(@"Error received...Delegate method");
}

- (void)channel:(NMSSHChannel *)channel didReadRawData:(NSData *)data{
    NSLog(@"Read Raw Data...Delegate method");
}
```
Connection to the server, sending a single line command and acknowledgement back from the server in Console is OK.

I have decent idea how to pass values from one View Controller to another using delegate (went through few tutorials with practical implementation).

With the same knowledge I am attempting to get response from delegate methods parts of NMSSH library but it's driving me round and round. I've found http://cocoadocs.org/docsets/NMSSH/2.2.1/ pretty nice API of this library but with my limited knowledge of iOS, I'm bit stuck.

[session.channel execute:@"command" error:&error]; NSLog(@"Response from device: %@", response); I can confirm on server, the command is being executed and in iOS Console the response coming back from server. Hence session.authorized is working with no issues. I also tried few more combination setting delegate outside session.authorized.

I'm running it on simulator, not on physical iPhone. is it a issue?

Any help would be much appreciated. 

I just realized, I posted this is Issues section, rather than Wiki. If required I'll move it from here. :)

**Comment by Frugghi** [comment]
I edited your post because the code was unreadable!

The methods of `NMSSHChannelDelegate` are called when the channel is in shell mode (see [`startShell:`](https://github.com/Lejdborg/NMSSH/blob/4449c71d58f3032a0a3e34321fe6772988444354/NMSSH/NMSSHChannel.m#L307)) but the method `execute:error:` use the channel in command mode. `session:didDisconnectWithError:` is not called because you don't disconnect the session.
Please note that `session` will be released at the end of `serverConnect:`, you should store the session in a property of `CustomViewController`.
