### ISSUE TITLE
How to read response from the server asynchronously?

### ISSUE THREAD

**Issue by mohammedmoinuddin80** [Lejdborg/NMSSH#147]
If I use execute method which return response from server after success, but shell will be closed. So I thought of using writeCommand instead but this method does not return server response, I've to rely on  didReadData method to catch server responses. 

I want to read server response immediately after execution of command successfully. I'm not very sure how to acheive this and what I'm missing here. 

Thanks in advance.

**Comment by Frugghi** [comment]
You can use the synchronous api (`execute`) in a background thread or you can use the async branch (see #80 for more info).
