### ISSUE TITLE
compile NMSSH for armv7k

### ISSUE THREAD

**Issue by Darkmelman** [Lejdborg/NMSSH#151]
Hello,

is it possible to compile the NMSSH framework for the armv7k architecture?

I think it is needed for the watch-os apps...

When i try to build NMSSH-ios project as watch-OS target with armv7k, i get the following error messages...

![image](https://cloud.githubusercontent.com/assets/8094432/9423144/252fcbf2-48b8-11e5-85df-48f61dc71318.png)

Thanks for your help!!!

Regards,

DarkMelman

**Comment by giuliomol** [comment]
Hello,
news about resolution?

Thanks

**Comment by Frugghi** [comment]
Does WatchOS have `CFNetwork` framework?

**Comment by giuliomol** [comment]
No, CFNetwork framework is not one of the available frameworks in watchOS 2

**Comment by Frugghi** [comment]
Unfortunately `CFNetwork` is required, we use it to manage the socket and perform hostname resolution.
