### ISSUE TITLE
NMSSH compatibility to xcode 7 beta x

### ISSUE THREAD

**Issue by Darkmelman** [Lejdborg/NMSSH#152]
Hello,

i am not able to compile the NMSSH-IOS project with xcode 7 beta 5 with the different architectures.
Is it possible, that NMSSH isn´t compatible to xcode 7 beta?

Thanks a lot, regards,

DarkMelman

**Comment by Lejdborg** [comment]
I have not yet tested NMSSH with Xcode 7. What kind of errors are you getting?

**Comment by Darkmelman** [comment]
Hello,

thanks for the fast reply. The problem is, i need to compile the NMSSH-ios project with bitcode enabled=yes because WatchKit needs bitcode enabled.

When i run "build" i get the following errors:

![image](https://cloud.githubusercontent.com/assets/8094432/9447411/800747ae-4a97-11e5-8365-7f79777f8eb4.png)

Thanks,

DarkMelman

**Comment by Frugghi** [comment]
You need to link the `CFNetwork` framework to your target
