### ISSUE TITLE
Not able to perform execute command

### ISSUE THREAD

**Issue by RohitArora28** [Lejdborg/NMSSH#154]
Hi,

I am not able to use shell command using library, for that we first authenticate using following method (BOOL)authenticateByPublicKey:(NSString *)publicKey
                     privateKey:(NSString *)privateKey
                    andPassword:(NSString *)password
and than I  set requestPty to YES, call startShell method and than send commands using method
- (BOOL)write:(NSString *)command error:(NSError **)error timeout:(NSNumber *)timeout

But my problem is we don't want to use shell due to echo issues and want to use execute command for that again I can authenticate successfully using above method, set requestPty to YES, and than call execute method
- (NSString *)execute:(NSString *)command error:(NSError **)error timeout:(NSNumber *)timeout
but every time I call execute method it hangs in the infinite do while loop in NMSSHChannel.m file

Am I doing anything wrong, please help.

Regards,
Rohit Arora

**Comment by Lejdborg** [comment]
Don't run `requestPty = YES` if you don't want to run in shell mode.

**Comment by RohitArora28** [comment]
I removed this line and even tried with setting requestPty to NO but none of the approach worked. 
Can you suggest any other workaround.

I want to use execute instead of shell because when we are using shell we get echo of the request sent.

**Comment by Lejdborg** [comment]
As per the README (https://github.com/Lejdborg/NMSSH#what-does-it-look-like):

```objective-c
NMSSHSession *session = [NMSSHSession connectToHost:@"127.0.0.1:22"
                                       withUsername:@"user"];

if (session.isConnected) {
    [session authenticateByPassword:@"pass"];

    if (session.isAuthorized) {
        NSLog(@"Authentication succeeded");
    }
}

NSError *error = nil;
NSString *response = [session.channel execute:@"ls -l /var/www/" error:&error];
NSLog(@"List of my sites: %@", response);

[session disconnect];
```
