### ISSUE TITLE
Method descriptions not clear

### ISSUE THREAD

**Issue by mikeCalvir** [Lejdborg/NMSSH#273]
I've got back to an old project and want to add auto-resume-download of a file to an app.

So this method:
- (BOOL)resumeFileAtPath:(NSString *)localPath toFileAtPath:(NSString *)path progress:(BOOL (^)(NSUInteger delta, NSUInteger totalBytes))progress;

Looks promising. 
But is this only for resuming an upload? How to even tell? "writing" a file can be in either direction, how do we know what paths are where? "LocalPath" - local to what? The calling program, or the SFTP connection?

I'm finding I have to dig down into the code each time to try and work out what the method means, and the method documentation doesn't provide any more contextual information. 

"Start or resume writing the contents of a file"

Sure, that seems clear from the method name - but are we resuming FROM the sftp server or TO it? And where is the corresponding method for the other direction?

Apologies for complaining about what has been a very reliable and excellent framework! I'm struggling to find a way to resume a download that was interrupted (eg network dropped), and no doubt it is my stupid fault :)

**Comment by Jan-E** [comment]
I happen to be responsible for the Resume methods. The description is in the .h file:
https://github.com/NMSSH/NMSSH/blob/master/NMSSH/NMSFTP.h#L250
> If no file exists, one is created.

Localpath is local for the calling program, i.e. the client (= your app) not the server. AFAIK there is no implementation for resuming downloads.

**Comment by mikeCalvir** [comment]
Thanks Jan-E. 
A shame for resuming downloads. I think most sftp servers do support it though?

I hope you see what I mean for the methods - just a little context for each method would be v useful to make it clearer what direction is intended. I get the impression that "contentsOf" is for "downloading" and "writeSomething" is for uploading, in general.
