### ISSUE TITLE
Socket connection successful but then fail to establishing SSH session

### ISSUE THREAD

**Issue by kiritoty** [Lejdborg/NMSSH#284]
I was able to SSH into my IoT device yesterday, but this morning when I try to connect it again. it fails to establish SSH session.

```
2021-08-25 09:25:53.501096-0400 [1387:464804] NMSSH: Socket connection to 192.168.77.30 on port 22 succesful
2021-08-25 09:25:53.551438-0400 [1387:464804] NMSSH: Failure establishing SSH session
```

It seems like socket connection success and then fails.

Any help is appreciated.

**Comment by noisewuwei** [comment]
hello.did you fix it?

**Comment by kiritoty** [comment]
> hello.did you fix it?

The problem for me is our IoT device has a security update, which changes the kex algorithm from curve25519-sha256@libssh.org to curve25519-sha256.

The precompiled version of libssh in this repo does not support curve25519-sha256. So you need to run this script to replace the libssh.
https://github.com/Frugghi/iSSH2

After replacing the libssh, everything running fine.

**Comment by noisewuwei** [comment]
Thanks!!!

**Comment by speam** [comment]
same issue, can use this repo directly:
https://github.com/speam/NMSSH
