### ISSUE TITLE
Fail to build the framework

### ISSUE THREAD

**Issue by BenHuiHui** [Lejdborg/NMSSH#39]
Hi I follow the steps but I cannot get the framework for iOS but OS X version works fine. (There is nothing inside the framework after building)

**Comment by coernel** [comment]
Could you provide us with your solution maybe? I just cloned NMSSH and I can't get it to build as well, as in there's no file n he output folder. Others seem to have the same problem as well: 

http://stackoverflow.com/questions/27151611/building-nmssh-for-ios 

Thanks in advance!

**Comment by Frugghi** [comment]
@coernel You should open an other issue. Btw the framework builds correctly on my Mac (Yosemite and Xcode 6.1)
