### ISSUE TITLE
Crash During Write/Read

### ISSUE THREAD

**Issue by nlssh** [Lejdborg/NMSSH#81]
Hi,
I've used your library to do an iPad app connecting to a remote SSH server for the last few weeks. The library is a great help but I have a problem when writing many commands at the same time on the shell. 
Here is the steps of my app:
1. Open a session with SSH session connection and authentication.
2. Set a channel with no requestPty and use startShell: to read data coming from the 
   server through channel didReadData: delegate.
3. Sending commands to the server through channel write: error: timeout: with
   dispatch_async on a serial queue.
   The app works fine when I send a command ( through button's click) once at a time, but it crashes when I tried to send the same command many times (clicking button really fast) to the shell with error like this:
   Assertion failed: (remainbuf >= Assertion failed: (remainbuf >=0), function _libssh2_transport_0), function _libssh2_transport_read, file transport.c, line 349 read, file transport.c, line 349), 
   Besides responses for the commands, the server dumps out different kinds of data and that might be the cause of the problem. I tried different things from the app side to avoid the error but was not successful. Could you give me some suggestion about this situation? Thanks for the help
   Regards,
   nlssh

**Comment by pkMinhas** [comment]
I am facing a similar issue. Is there any fix available?
