### ISSUE TITLE
Assertion failed: (remainbuf >= 0), function _libssh2_transport_read, file transport.c, line 345.

### ISSUE THREAD

**Issue by ghost** [Lejdborg/NMSSH#83]
My app crashes randomly when the terminal is beeing started and connected with the attached error logs. Around 3 of 5 times the app crashes completely and 2 of 5 times the SSH connection and terminal works perfect and as expected. 

The implementation is taken from the PTYExample, so there's nothing much special or homegrown. I guess there's a issue with memory management in the NMSSH lib or libssh lib - which conflicts with IOS7.

What could be the cause?

Heres crash log example a:

```
2014-05-10 00:02:34.436 [5788:1303] NMSSH: Socket connection to 10.0.0.1 on port 22 succesful
2014-05-10 00:02:35.076 [5788:1303] NMSSH: The host's fingerprint is 40:6E:E9:0A:BD:7E:2D:BF:65:2B:BB:0B:12:11:BF:EF
2014-05-10 00:02:35.235 [5788:1303] NMSSH: Starting shell
Assertion failed: (remainbuf >= 0), function _libssh2_transport_read, file transport.c, line 345.
Assertion failed: (remainbuf >= 0), function _libssh2_transport_read, file transport.c, line 345.
```

Another crash log example b:

```
2014-05-10 00:09:08.495 [5892:3507] NMSSH: Socket connection to 10.0.0.1 on port 22 succesful
2014-05-10 00:09:09.574 [5892:3507] NMSSH: The host's fingerprint is 40:6E:E9:0A:BD:7E:2D:BF:65:2B:BB:0B:12:11:BF:EF
2014-05-10 00:09:09.794 [5892:3507] NMSSH: Starting shell
TerminalApp(5892,0xb031d000) malloc: *** error for object 0xbfa12e0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
2014-05-10 00:09:10.035 [5892:3507] NMSSH: Shell request error
```

Sometimes the library also crashes in NMSSHChannel.m at line 392 with EXC_BAD_ACCESS. The offending line is:

```
while ((rc = libssh2_channel_shell(self.channel)) == LIBSSH2_ERROR_EAGAIN) {
```

Thanks in advance

**Comment by Sumit19** [comment]
Hi @dschallert , I am also facing a same problem around 4-5 days. Can you help me to solved this problem.

**Comment by Chirag88** [comment]
Hi Sumit,

To fix this issue i used key value observer on the network class. Whenever there is a internet connectivity loss while data is getting downloaded, observer observe the change in connectivity then you should disconnect the SFTP session calling the below method.
- (void)disconnectSession {
    NetworkManager *obj=[NetworkManager sharedObject];
    obj.session = nil;
    obj = nil;
}

This fixed my issue.

**Comment by Sumit19** [comment]
Thank you @Chirag88  for quick reply but I have got the error on this line 
  while ((rc = libssh2_channel_shell(self.channel)) == LIBSSH2_ERROR_EAGAIN) . 
This is also resolved as per your above answer.

**Comment by Chirag88** [comment]
In my case app was crashing randomly. You can try this code call disconnect session method (setting the session obj to nil) whenever there is a connection loss. 
If the app tries to connect again then it will make a fresh connection.

**Comment by Sumit19** [comment]
@Chirag88 , My app crash only at the time of fresh login and the line in which error occur is  
 while ((rc = libssh2_channel_shell(self.channel)) == LIBSSH2_ERROR_EAGAIN) 
It will not happen every time.

**Comment by joshzngf** [comment]
Hi @Sumit19 , I'm having the same problem. I'm having random crash when calling startShell. Have you solved the problem? If you did, how? Thanks.

**Comment by Sumit19** [comment]
@joshzngf  Please refer this link https://github.com/Lejdborg/NMSSH/pull/80 and my problem solved by using a Asynchronous NMSSH Library and the link is https://github.com/Lejdborg/NMSSH.

**Comment by joshzngf** [comment]
@Sumit19 Ok I'll take a look, thanks!
