### ISSUE TITLE
malloc: pointer being freed was not allocated

### ISSUE THREAD

**Issue by ghost** [Lejdborg/NMSSH#84]
Hi everyone, about 3 of 5 times initializing an NMSSH connection I get a malloc() error :-1: 
I've set a malloc_errror_break breakpoint already which leads to:

```
  libsystem_malloc.dylib`malloc_error_break:
  0x2c5b7f9:  pushl  %ebp
  0x2c5b7fa:  movl   %esp, %ebp
  0x2c5b7fc:  subl   $0x8, %esp
  0x2c5b7ff:  nop    
  0x2c5b800:  nopl   (%eax)
  0x2c5b804:  addl   $0x8, %esp
  0x2c5b807:  popl   %ebp
  0x2c5b808:  ret    
```

**Comment by Sumit19** [comment]
Hi @dschallert , if i remove these line 

dispatch_async(self.sshQueue, ^{
    });

it slows down my app.

**Comment by Frugghi** [comment]
@Sumit19 the AsyncAPI branch fixes this issue.

**Comment by Sumit19** [comment]
Hi @Frugghi , Please give me a latest link of NMSSH Library.

**Comment by Frugghi** [comment]
[This](https://github.com/Lejdborg/NMSSH/tree/AsyncAPI) changes are not on master because the NMSFTP part is not asynchronous yet, if you need SFTP you can't use it.
