### ISSUE TITLE
Library not loaded...

### ISSUE THREAD

**Issue by necatkutlar** [Lejdborg/NMSSH#92]
Hi,

I am trying to link the nmssh-framework to my osx app, but I get the following error message. Does anyone have any idea, what it could be?
I build the nmssh-framework for 64 bit, no problems.
I added it as well as describe.

dyld: Library not loaded: @executable_path/../Frameworks/NMSSH.framework/Versions/A/NMSSH
  Referenced from: /Users/necat/Develop/OSX/PhotoIptcEdit/build/Debug/Photoiptcedit.app/Contents/MacOS/Photoiptcedit
  Reason: image not found

thanks for help,
regards necat

**Comment by gurinderhans** [comment]
It did not work for me :(

**Comment by Manuel83** [comment]
I have the same issue


```
dyld: Library not loaded: @rpath/NMSSH.framework/NMSSH
  Referenced from: /Users/manuelfritsch/Library/Developer/CoreSimulator/Devices/02C3DCBE-6EDA-4FF5-A1E5-B20E439EBDFE/data/Containers/Bundle/Application/3B53C782-44D8-40FB-9DB9-0D52DF233CCB/CraftBeerPi.app/CraftBeerPi
  Reason: image not found
(lldb) 

```
![image](https://cloud.githubusercontent.com/assets/5859486/17680685/c10bd4b8-6341-11e6-991d-49e4adfd2bb8.png)

**Comment by Lejdborg** [comment]
Manuel: click the + in Copy files and add NMSSH.framework
